// src/react/Counter.js
import React from 'react';
import ReactDOM from 'react-dom';

import CollarView from '../abstraction/CollarView';

class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    }
  }

  onDecrement() {
    this.props.view.send({
      actionType: 'DECREMENT'
    })
  }

  onIncrement() {
    this.props.view.send({
      actionType: 'INCREMENT'
    })
  }

  render() {
    return (
      <div className="react-counter">
        <div className="react-counter-value"><h1 className="counter-value">{this.state.count}</h1></div>
        <button className="react-counter-dec-btn press" onClick={this.onDecrement.bind(this)}>-</button>
        <span> </span> 
        <button className="react-counter-inc-btn press" onClick={this.onIncrement.bind(this)}>+</button>
      </div>
    )
  }
}



module.exports = function(selector, name) {
  let counter = new CollarView(selector, name);

  let reactComp = null;
  counter.setRenderer(function(state, done) {
    reactComp = ReactDOM.render(
      <Counter view={counter} />,
      document.querySelector(selector)
    )
    done();
  });

  counter.setUpdater(function(state, done) {
    reactComp.setState(state);
    done();
  });

  return counter;
};

// src/angular/Counter.js
import { Component, NgModule, NgZone, Injectable, ChangeDetectorRef } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import CollarView from '../abstraction/CollarView';

module.exports = function(selector, name) {
  let counter = new CollarView(selector, name);

  let viewState = {count : 0}
  let changeDetectorRef = null;

  class CounterComponent {
    static get annotations() {
      return [
          new Component({
            selector: "#angular-counter",
            template: `<div class="angular-counter-value"><h1 class="counter-value">{{ state.count }}</h1></div>
              <button class="angular-counter-dec-btn press" (click)="decrement()">-</button>
              <button class="angular-counter-inc-btn press" (click)="increment()">+</button>`,
          }),
        ];
    }

    static get parameters() {
      return [[ChangeDetectorRef]];
    }
      
    constructor(cdr) {
      console.log(cdr)
      changeDetectorRef = cdr;
      this.state = viewState;
    }

    increment() {
      counter.send({
        actionType: 'INCREMENT'
      });
    }

    decrement() {
      counter.send({
        actionType: 'DECREMENT'
      })
    }

  }

  class AppModule {
    static get annotations() {
      return [
        new NgModule({
          imports: [
            BrowserModule
          ],
          declarations: [
            CounterComponent
          ],
          bootstrap: [
            CounterComponent
          ]
        })
      ]
    }

    constructor() {}
  }

  counter.setRenderer(function(state, done) {
    platformBrowserDynamic().bootstrapModule(AppModule);
    done();
  });

  counter.setUpdater(function(state, done) {
    viewState.count = state.count;
    changeDetectorRef.detectChanges();
    done();
  });

  return counter;
};
